#Volume for the Notifications in %. You could raise it above 100%, I strongly advise against it.
#Reason that this is in the control of the enduser is partly to avoid troll attempts.
#These define the maximum volume usable by a lua script and the default volumes.
notification_volume = 100

#Volume for the channels (soundeffects) in %.
concurrent_volume = 100

#Volume for the queue
queue_volume = 100

#Volume % level for everything else while notification is sounding. Basically, a sound in the queue currently playing would be at 50% of the usual volume, if this value is 50
notification_difference = 50